dist: trusty
sudo: required

language: go

env:
  global:
    - secure: "SSGPlBUXMb2F3ycFEvRKHoftYy0UkIprwgtfOKXU/Uc359Qct+IrF/b8GuTd64tedXtnQE4z4fxqT8wdYRdNwUysmOvRyzlNTRhs1gocx5iL5El8+7F4we7wElh6ckt2Z5AVI5g0JOwYeQNURFhgDumN14K8XsOu7a2LzRBVFRn55z79xgTL+JnTI89JIWjz1QCr8Z054CMaK0MHJRLkgPnbnx1Skra3Wt16g29wRZLqLWoU8lyrLy9Ao/yHw/AJMCNie8ah7nNiOEdgPTcr/onZ/v+eVyaTvzE9UrmdeqpUpASypAAUnmZ9Q6QsU31dVxwbfPB0r8TzrqinCOYMnHbU/3fIz49Q+yv7RyifYsTlnx7+J79LmCvs7X+iKkmOprWdBRwUUxzDhwgIGnmBlYf0nKj9H2U3XFCYDnbRSI9ZugGBprs3t09w15gwq/wLM6DhY87zNhM4Vfb34ZXVBCEhtUXKUVbVthiPOWlHtbs0YympG/QCV+27tVIszgek8FFt6/fJeEh/APNadK9fuU01ozB01aXj0xMl3PlvoWWeQXDnyttHEWRaiVpbPKGoV5a7LPCVpWk5EOX8YNgHEUnjKwfzVBUriXAd+8zp0sx6TRdt1ts7x04NP1yFF1SCXXBpz/geOsfa2bBQyJx6y7CODcmW7fbcJLxmwdGlm6E="
    - secure: "Tr9KxWvfQS6BSF1qUqz1Q41le5k/c+L37Aq8wTPQcmXVu8nLv5T1QMarx64KfZ2qaQBRV+M6DwnJQM7HU/cWX9AKpdoAO2INqANfoFLh8XTR5ncHjaNTzi9aS7owxa+9t0yfKowq7s4dp96nqmwchYFtUxpzKo0TMOcQ1l1AGEu5liniXb9VOKgG8UAZsLgD6b2a80nn6NP1JehGGxcWsow0EzxalnJ8Cv78YTLmqGNowYh5UmkhjkxqE4TskQafRd2qtYMPvxnC2CFd8G3qMlbBzCxM02lGKwbr/Vi41hcSyD3uuyaKVHr/g5qLcp/HNyrUGTREL1UvWkWjlL6ovuh6uHYlnpVwQkX5fzUH7z2hlr9HjQ3Tu6Sbh1CX5QBR5PUkvoOfdx0BHTmTTw2xkvUDHarqZT1OkMuUplCY/VMnJaqa5ko126r8CyKYqRoT4HQuqa6szVawGiB211VCQXJRVyLYtKUGO6mmnMUoi5H676/sv6c9py8bieMoyEyrI87lS0AhQ6QLnTjNbEO5xt6vFi7rEgcctD5nuEBwb/X2bmM2OdZFYXrIbXaZfq7fRKyzCQthfceCmySExOGI9ndCE/mS68X6NNFBVsVwb7zt0zSY6oGlf0/N2CR5sf8gwKYG1scr5Jyqmuifvqv433zepA0Sxj6WqC3ixlssNd8="
jobs:
  include:
    # YAML alias, for settings shared across the tests
    - &base-test
      stage: test
      go_import_path: github.com/redhat-developer/odo
      go: "1.11"
      install:
        - make goget-tools
      script:
        - make bin
        - make validate
        - make test

    - <<: *base-test
      script:
        - make bin
        - make validate
        - make test-coverage
      after_success:
        # submit coverage.txt to codecov.io 
        - bash <(curl -s https://codecov.io/bash)

    # Run main e2e tests
    - <<: *base-test
      stage: test
      script:
        - ./scripts/oc-cluster.sh
        - make bin
        - sudo cp odo /usr/bin
        - oc login -u developer 
        - make test-main-e2e

    # Run component e2e tests
    - <<: *base-test
      stage: test
      script:
        - ./scripts/oc-cluster.sh
        - make bin
        - sudo cp odo /usr/bin
        - oc login -u developer
        - make test-cmp-e2e

    # test installation script on linux
    # - stage: test
    #   services:
    #     - docker
    #   install:
    #     - true
    #   script:
    #     ./scripts/test-install.sh
    # test installation script on macOS
    - state: test
      os: osx
      install:
        - true
      script:
        ./scripts/install.sh

    - stage: deploy
      go_import_path:  github.com/redhat-developer/odo
      go: "1.11"
      install:
        - make goget-tools
        - gem install fpm
        - sudo apt-get -qq update
        - sudo apt-get install -y rpm
        # Ideally following commands should be in before_deploy section
        # but travis-ci runs before_deploy for every provider. We don't want that.
        - make prepare-release
        - ./scripts/generate-bintray-json.sh
        - make packages
      script: skip
      deploy:
        # upload gziped binaries to github release page
        - provider: releases
          api_key:
            secure: jKRaI1sHOQO1g1qVVEOCfe4Wu90Sj586IVB94mogAKukqh9f2OMELAIgMLjKcuzD25AawGLzSIo2e1Q98f1+tVN5m7XvRtPn4Z7IVPV35rSuFh+c+ZFZB0OaOxmSU81f8qo5ZvSyljYSm1mQ2TFMrVjPSOdmACByo6vB4RboCRQTJSevMLwRboN7Qg8Sh5Sdy8ug7F0opLxhkeht9N17WdIZ6D7ZakaK6V2065iTNb83EsXbHF8QKM6fLptGoPfZDfsJRXKavHpzKGjs8yET1vgYiSEqh51X92nbqnpnLtj+vQn+gFNOiFvrnHK+oyaWX2L6qqp8oemRDI0FqbuaBNL4107VvNXsN8k6uuOrgFxQVSW0N2KMggBn1voV3MPaaRlWysgTl07PYMH+dNCyo9RMPcY4Fwcp1Om2ZY5S4tspDyt4Ie9WRzJDnhNxfsIh3LUVCYJqfpF1uc/9BMGDitnXTbrgktxWBNd4J7IIZMkyxnREkrhnm6xU+F2OYidSzWONxYrsvchxVTdTJkVzcmLOGK+w4KSpFFQIRa98vBrNjd67YLHeZIBlf8A9Z2YI7E6eOf8qA7gcyruykVT2I865TkSSYI59ljejdXF+fIuUk0kuLzRVjCSDea88duGGOPAz92MtvQu4G2rDwPgU4squqBacpFtR2ULxXfbojk0=
          draft: true
          prerelease: true
          file_glob: true
          file: "./dist/release/*"
          skip_cleanup: true
          on:
            tags: true
            repo: anmolbabu/odo
        # upload packages to bintray repositories
        - provider: script
          skip_cleanup: true
          script:
            - make upload-packages
          on:
            tags: true
        - provider: script
          skip_cleanup: true
          script:
            - make upload-packages
          on:
            branch: master
